# Generated by Django 3.2 on 2021-04-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoosfit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_date', models.DateTimeField(verbose_name='streak')),
                ('streak_number', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
