# Generated by Django 3.2 on 2021-04-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoosfit', '0002_streak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streak',
            name='streak_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
