# Generated by Django 3.1.7 on 2021-04-16 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoosfit', '0002_auto_20210415_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='date',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
    ]
