# Generated by Django 3.2 on 2021-04-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoosfit', '0005_alter_profile_previous_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='streak_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
