# Generated by Django 3.1.7 on 2021-04-19 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoosfit', '0003_auto_20210416_1649'),
        ('hoosfit', '0006_alter_profile_streak_number'),
    ]

    operations = [
    ]
