# Generated by Django 3.1.7 on 2021-04-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoosfit', '0008_profile_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='previous_login',
        ),
        migrations.AddField(
            model_name='profile',
            name='previous_workout',
            field=models.DateField(null=True, verbose_name='streak'),
        ),
    ]
