# Generated by Django 3.1.7 on 2021-04-19 04:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoosfit', '0009_auto_20210419_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='previous_workout',
            field=models.DateField(default=datetime.date(2021, 4, 18)),
        ),
    ]
