# Generated by Django 3.1.7 on 2021-04-19 04:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hoosfit', '0010_auto_20210419_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='previous_workout',
            field=models.DateField(default=datetime.datetime(2021, 4, 18, 4, 22, 40, 458402, tzinfo=utc)),
        ),
    ]
