# Generated by Django 3.1.7 on 2021-04-19 04:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hoosfit', '0011_auto_20210419_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='previous_workout',
            field=models.DateField(default=datetime.datetime(2021, 4, 18, 4, 23, 13, 114735, tzinfo=utc)),
        ),
    ]
