# Generated by Django 3.1.7 on 2021-04-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoosfit', '0013_auto_20210419_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='exercise',
        ),
        migrations.AddField(
            model_name='award',
            name='best_reps',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='award',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='award',
            name='exercise_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='award',
            name='award_name',
            field=models.CharField(max_length=200),
        ),
    ]
