# Generated by Django 3.1.7 on 2021-04-22 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoosfit', '0014_auto_20210419_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='award_name',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='award',
            name='exercise_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='previous_workout',
            field=models.DateField(default=datetime.date(2021, 4, 21)),
        ),
        migrations.AlterField(
            model_name='workout',
            name='workout_name',
            field=models.CharField(max_length=50),
        ),
    ]
